# Generated by Django 4.2.7 on 2024-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Pol', models.CharField(max_length=25)),
                ('Por', models.CharField(max_length=25)),
                ('Pod', models.CharField(max_length=25)),
                ('FPod', models.CharField(max_length=25)),
                ('Weight', models.FloatField(max_length=25)),
                ('CBM', models.CharField(max_length=25)),
                ('Volume', models.FloatField(max_length=25)),
                ('Hazard', models.CharField(max_length=25)),
                ('Stackable', models.CharField(max_length=25)),
            ],
        ),
    ]
