# Generated by Django 4.2.7 on 2024-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackID', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=10)),
                ('Details', models.CharField(max_length=1000)),
            ],
        ),
    ]
